FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g 999 docker-host || true && \
    usermod -aG 999 jenkins

USER jenkins