pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -f ci_cd/Dockerfile -t videofactory .'
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    docker run --rm videofactory ruff check .
                '''
            }
        }

        stage('Tests') {
            steps {
                sh '''
                    docker run --rm videofactory \
                    python3.11 -m pytest \
                    --cov=. \
                    --cov-report=term-missing \
                    --cov-fail-under=70
                '''
            }
        }
    }

    post {
        success {
            echo 'CI pipeline uspešno završen.'
            echo 'Docker image je uspešno napravljen, Ruff lint je prošao, svi testovi su prošli i coverage je najmanje 70%.'
        }

        failure {
            echo 'CI pipeline neuspešan.'
            echo 'Proveri Docker build, Ruff lint ili testove.'
        }
    }
}