pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -f ci_cd/Dockerfile -t videofactory .'
            }
        }

        stage('Tests') {
            steps {
                sh 'docker run --rm videofactory python3.11 -m pytest'
            }
        }
    }
}